theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.81.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false